name: Vizzz

on:
  push:
    branches:
      - develop

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ap-southeast-1

      - name: deploy

        run: |

          zip -r deploy.zip src requirements.txt main.py

          aws lambda update-function-code --function-name=generate_viz_devs --zip-file=fileb://deploy.zip
